# Site settings
title: 둘리의 개발이야기
description: "둘리의 개발이야기"
url: "http://www.dyutibarma.github.io/monochrome"
author:
  name:
    ko: "둘리"
    en: "dooly"
  email: "sonaky47@gmail.com"
  url: "https://thereviewindex.com"

# Build settings
baseurl: /monochrome # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
